on:
  push:
    branches:
      - instance-stage
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '20.18.0'
          ref: instance-stage
          

      - name: Clean dependencies
        run: |
          rm -rf node_modules package-lock.json
          
      - name: install dependency
        run: npm install
      - name: install build
        run: npm run build-stage
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          host: '${{ secrets.HOST_DNS }}'

        env:
          SSH_PRIVATE_KEY: '${{ secrets.EC2_SSH_KEY }}'
          REMOTE_HOST: '${{ secrets.HOST_DNS }}'
          REMOTE_USER: '${{ secrets.USERNAME }}'
          
      - name: Restart services
        run: pm2 restart 1
